import { useMemo } from 'react'
import { useEezStore } from '@/store/eezStore'
import { useWeatherStore } from '@/store/weatherStore'
import { useIncidentFeedStore } from '@/store/incidentFeedStore'
import { isDemoMode } from '@/lib/demo/mode'
import type { MapLayerId } from '@/store/mapStore'

/**
 * App-owned overlays the map draws unconditionally.
 *
 * These have no data feed to gate on: the slick, the AIS trails, the forecast
 * drift and the attribution rings are generated by the simulation itself. The
 * layer *drawer* leaves them out of its toggle list because they are part of the
 * scene rather than something an operator switches on and off, which is exactly
 * why the legend used to mark them as unavailable while they were plainly
 * visible on the map.
 */
export const APP_OWNED_MAP_LAYERS: readonly MapLayerId[] = [
  'slick',
  'vesselTrails',
  'drift',
  'attribution',
] as const

/**
 * Which layers the command-centre map can actually draw right now.
 *
 * The observation and simulation layers are app-owned and always render. The
 * environment layers are gated on their live feed status, so the map never
 * advertises a layer whose data source is not connected. The lane, pass and
 * vector-field layers are synthetic demo context, so they are offered only while
 * the controlled demo is running.
 *
 * This lives in one place because the layer drawer and the map legend both need
 * it, and two copies of "is this layer available" is how a legend ends up
 * labelling a layer the map cannot draw.
 *
 * The result covers the app-owned overlays too, so a consumer asking "can the map
 * draw this?" gets one answer whether the layer is a toggle or part of the scene.
 */
export function useAvailableMapLayers(): Set<MapLayerId> {
  const eezStatus = useEezStore((s) => s.status)
  const weatherStatus = useWeatherStore((s) => s.status)
  const incidentStatus = useIncidentFeedStore((s) => s.status)

  return useMemo(() => {
    const s = new Set<MapLayerId>(['sarSlicks', 'vessels', ...APP_OWNED_MAP_LAYERS])
    if (eezStatus === 'available') s.add('eez')
    if (weatherStatus === 'available') s.add('weather')
    if (incidentStatus === 'available') s.add('incidents')
    if (isDemoMode()) {
      s.add('sarFootprint')
      s.add('shippingLanes')
      s.add('currents')
      s.add('wind')
    }
    return s
  }, [eezStatus, weatherStatus, incidentStatus])
}
